apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: minicart
  description: The Minicart is a block that displays a summary list of all items
    added to the shopping cart, fetched from the Checkout OrderForm API.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/minicart
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: 6WQ27P7P
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
