export default {
  cacheId: 'b3c2c30dd46a41eeb242de7ab51dd268',
  orderFormId: 'b3c2c30dd46a41eeb242de7ab51dd268',
  value: 11252.49,
  totalizers: [
    {
      id: 'Items',
      name: 'Items Total',
      value: 1125249,
      __typename: 'vtex_storegraphql_2_50_1_Totalizer',
    },
  ],
  items: [
    {
      id: '2000539',
      name: 'Long Sleeve Shirt Regular',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155487-55-55/Frame-7.jpg?v=636793837686400000',
      detailUrl: '/long-sleeve-shirt/p',
      skuName: 'Regular',
      quantity: 1,
      sellingPrice: 9449.99,
      listPrice: 9449.99,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      __typename: 'vtex_storegraphql_2_50_1_OrderFormItem',
    },
    {
      id: '31',
      name: 'Fashion Eyeglasses 1',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155468-55-55/Frame-5.jpg?v=636793755542000000',
      detailUrl: '/fashion-eyeglasses/p',
      skuName: '1',
      quantity: 1,
      sellingPrice: 1540,
      listPrice: 1900,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      __typename: 'vtex_storegraphql_2_50_1_OrderFormItem',
    },
    {
      id: '35',
      name: 'Classic Shoes Classic Pink',
      imageUrl:
        'http://storecomponents.vteximg.com.br/arquivos/ids/155470-55-55/Frame-11.jpg?v=636793763155730000',
      detailUrl: '/classic-shoes/p',
      skuName: 'Classic Pink',
      quantity: 1,
      sellingPrice: 262.5,
      listPrice: 262.5,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      __typename: 'vtex_storegraphql_2_50_1_OrderFormItem',
    },
  ],
  shippingData: {
    address: null,
    availableAddresses: [],
    __typename: 'vtex_storegraphql_2_50_1_OrderFormShippingData',
  },
  clientProfileData: null,
  storePreferencesData: {
    countryCode: 'BRA',
    currencyCode: 'BRL',
    timeZone: 'E. South America Standard Time',
    __typename: 'vtex_storegraphql_2_50_1_StorePreferencesData',
  },
  itemMetadata: null,
  __typename: 'vtex_storegraphql_2_50_1_OrderForm',
}
